#ifndef CONSTANTS_H
#define CONSTANTS_H

//Possible values for peltier cell activation
#define PELTIER_OFF         0
#define PELTIER_COOLING_ON  1
#define PELTIER_HEATING_ON  2
#define PELTIER_UNDEFINED   3

//POSSIBLE VALUES FOR TEMP CONTROL UNIT STATUS
#define TEMPCTRL_OFF        0
#define TEMPCTRL_HEATING_1  1
#define TEMPCTRL_HEATING_2  2
#define TEMPCTRL_HEATING_3  3
#define TEMPCTRL_HEATING_4  4
#define TEMPCTRL_COOLING_1  5
#define TEMPCTRL_COOLING_2  6
#define TEMPCTRL_COOLING_3  7
#define TEMPCTRL_COOLING_4  8
#define TEMPCTRL_UNDEFINED  9

#define UNDEFINED_FLOAT 0x7F7FFFFF
#define UNDEFINED_U8  0xFF
#define UNDEFINED_U16 0xFFFF
#define UNDEFINED_U32 0xFFFFFFFF

#define TASKID_TEMPCTRL         0
#define TASKID_TEMPSENSORS      1
#define TASKID_PRESSURESENSORS  2
#define TASKID_PWMMOSFETS       3

//Protection threshold values
#define PELTIER_HOTSIDE_MAXTEMP 80
#define PELTIER_HOTSIDE_WARNINGTEMP 70
#define PELTIER_WATER_CONDENSATIONTEMP 5
#define PELTIER_MINIMUM_TIME_FOR_CYCLING_S 60
#define HEATEXCHANGER_MINIMUM_OUTLETWATER_TEMP 5

#endif

